[package]
authors = ["adoo <Adoo@outlook.com>"]
edition = "2021"
name = "ribir"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ribir_gpu = {path = "../gpu", version = "*"}
ribir_core = {path = "../core"}
ribir_widgets = {path = "../widgets"}
lyon_algorithms = "1.0.1"
lyon_path = "1.0.1"
euclid = "0.22.6"

[dev-dependencies]
env_logger = "0.7.1"

[features]
default = ["wgpu_gl"]
wgpu_gl = ["ribir_gpu/wgpu_gl"]
